printWidth: 100
tabWidth: 2
useTabs: false
singleQuote: true

overrides:
  - files: '*.php'
    options:
      parser: php
      tabWidth: 4
      useTabs: true
      printWidth: 120
      singleQuote: true
      trailingCommaPHP: false

plugins:
  - '@prettier/plugin-php'
